site_name: mkdocs-section-index
site_url: 'https://example.org'

nav:
  - Frob: index.md
  - Baz: baz.md
  - Borgs:
    - borgs/index.md
    - Bar: borgs/bar.md
    - Foo: borgs/foo.md

theme:
  name: material

plugins:
  - search
  - section-index
